Samples.AdminUI.UserSettings/Models/ClaimDto.cs
using System;

namespace Samples.AdminUI.UserSettings.Models
{
    public class ClaimDto
    {
        public ClaimDto() { }

        public ClaimDto(string type, string value)
        {
            Type = type ?? throw new ArgumentNullException(nameof(type));
            Value = value; 
        }

        public string Type { get; set; }
        public string Value { get; set; }
    }
}

Samples.AdminUI.UserSettings/Models/ErrorViewModel.cs
namespace Samples.AdminUI.UserSettings.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Samples.AdminUI.UserSettings/Models/ManageProfileModel.cs
using System.Collections.Generic;

namespace Samples.AdminUI.UserSettings.Models
{
    public class ManageUserClaimsModel
    {
        public List<ClaimDto> Claims { get; set; }
    }
}

Samples.AdminUI.UserSettings/Models/UserClaimsDto.cs
using System.Collections.Generic;

namespace Samples.AdminUI.UserSettings.Models
{
    public class UserClaimsDto
    {
        public string Subject { get; set; }

        public List<ClaimDto> Claims { get; set; }
    }
}

Samples.AdminUI.UserSettings/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Samples.AdminUI.UserSettings.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Samples.AdminUI.UserSettings/Controllers/ManageUserClaimsController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Samples.AdminUI.UserSettings.Models;
using Samples.AdminUI.UserSettings.Services;

namespace Samples.AdminUI.UserSettings.Controllers
{
    [Authorize]
    public class ManageUserClaimsController : Controller
    {
        private readonly IManageUserClaimsService claimsService;

        public ManageUserClaimsController(IManageUserClaimsService claimsService)
        {
            this.claimsService = claimsService ?? throw new ArgumentNullException(nameof(claimsService));
        }
        
        [HttpGet]
        public async Task<IActionResult> UserClaims()
        {
            var model = new ManageUserClaimsModel
            {
                Claims = await claimsService.GetUserClaims()
            };

            return View(model);
        }
        
        [HttpPost]
        public async Task<IActionResult> UserClaims(ManageUserClaimsModel model)
        {
            await claimsService.UpdateUserClaims(model.Claims);

            return RedirectToAction("UserClaims");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Samples.AdminUI.UserSettings/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <br/>
    <h2>AdminUI UserSettings Example App</h2>
    <br/>
    Click @Html.ActionLink("here", "UserClaims", "ManageUserClaims") to manage your claims
</div>

Samples.AdminUI.UserSettings/Views/ManageUserClaims/UserClaims.cshtml
@model Samples.AdminUI.UserSettings.Models.ManageUserClaimsModel
@{
    ViewData["Title"] = "Manage Profile";
}

<br />
<div class="row">
    <div class="col-md-8">
        @if (Model.Claims.Count == 0)
        {
            <p>No editable claims avaliable</p>
        }
        else
        {
            <form method="post" asp-route="UpdateUserClaims">
                @for (int i = 0; i < Model.Claims.Count; i++)
                {
                    <div class="form-group">
                        <label asp-for="Claims[i].Type">@Model.Claims[i].Type</label>
                        <input asp-for="Claims[i].Type" value="@Model.Claims[i].Type" hidden />
                        <input asp-for="Claims[i].Value" class="form-control" id="@Model.Claims[i].Value" value="@Model.Claims[i].Value" required />
                    </div>
                }

                <button class="btn btn-primary" type="submit" value="Submit">Update Claims</button>
            </form>
        }
    </div>
</div>

Samples.AdminUI.UserSettings/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserSelfManagementExample</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a></li>
                    <li><a asp-area="" asp-controller="ManageUserClaims" asp-action="UserClaims">Manage Profile</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - User Self Management Example</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>